### ISSUE TITLE
Warning: validateDOMNesting(...) when using JSXMessage

### ISSUE THREAD

**Issue by fritzzu** [twihike/chat-ui-react#11]
Hi,
when using JSXMessage a Warning: validateDOMNesting(...)  is raised if the JSX element used as content uses elements that cannot be descendant of `<p>`. 
I think it's caused by these lines in MuiMessage.tsx :

` <Typography
            variant="body1"
            style={{ overflowWrap: 'break-word', whiteSpace: 'pre-wrap' }}
          >
            {/* eslint-disable-next-line @typescript-eslint/ban-types */}
            {message.content as object}
          </Typography>`

Probably if the message.content isn't a string it would be better to use a generic `<div>` and not a `<Typography>` that produces a `<p>` element.
Thanks.

**Comment by twihike** [comment]
Hi,
thanks for the report.
I fixed it and released v0.2.13.
Could you check it.

Thank you.

**Comment by fritzzu** [comment]
Thanks!
